# vim: set filetype=helm:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  postgresql.conf: |+
    {{- .Files.Get "files/config/postgresql.conf" | nindent 4 }}
  pg_hba.conf: |+
    {{- .Files.Get "files/config/pg_hba.conf" | nindent 4 }}
  replication-for-master.conf: |+
    {{- include "postgresql-cluster.postgres.configurationStanzaForReplicationInMaster" . | nindent 4 }}
  replication-for-standby.conf: |+

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-init-scripts
data:
  {{- (.Files.Glob "files/db-init-scripts/*.sh").AsConfig | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
data:
  {{- (.Files.Glob "files/scripts/*.sh").AsConfig | nindent 2 }}

