# vim: set filetype=helm:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- (.Files.Glob "files/config/*.conf").AsConfig | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-init-scripts
data:
  {{- (.Files.Glob "files/db-init-scripts/*.sh").AsConfig | nindent 2 }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
data:
  {{- (.Files.Glob "files/scripts/*.sh").AsConfig | nindent 2 }}

