# vim: set filetype=helm: 

{{- $fullname := (include "postgresql-cluster.fullname" .) -}}
{{- $serviceName := (include "postgresql-cluster.postgres.serviceName" .) -}}
{{- $serviceDomain := (include "postgresql-cluster.postgres.serviceDomain" .) -}}
{{- $clusterDomain := (include "postgresql-cluster.clusterDomain" .) -}}
{{- $masterHost := printf "%s-master-0.%s" $fullname $serviceDomain -}}

{{- $numOfReplicas := (eq .Values.pgpool.loadBalance "sync" | ternary (int .Values.postgres.replicasToSync) (int .Values.postgres.replicas)) -}}

{{/* Check that: poolSize * numProcs <= maxNumConnections - (numOfReservedConnections = 4) */}}
{{- if gt (mul .Values.pgpool.numProcs .Values.pgpool.poolSize) (sub .Values.postgres.maxNumConnections 4) -}}
{{ fail "Must increase the max number of connections for the PostgreSQL backend!" }}
{{ end -}}

# manifests

---
{{- if .Values.pgpool.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-pgpool
  labels:
    {{- include "postgresql-cluster.labelsForPgpool" . | nindent 4 }}
spec:
  replicas: {{ .Values.pgpool.replicas }}
  selector:
    matchLabels:
      {{- include "postgresql-cluster.selectorLabelsForPgpool" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}{{ toYaml .Values.podAnnotations | nindent 8 }}{{- end }}
        {{- if .Values.pgpool.podAnnotations }}{{ toYaml .Values.pgpool.podAnnotations | nindent 8 }}{{- end }}
      labels:
        {{- include "postgresql-cluster.selectorLabelsForPgpool" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "postgresql-cluster.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.pgpool.securityContext.gid }}
      imagePullSecrets: 
        {{- toYaml .Values.pgpool.imagePullSecrets | nindent 8 }}
      volumes:
      - name: pgpool-admin-password
        secret:
          secretName: {{ include "postgresql-cluster.pgpoolAdminPassword.secretName" . }}
          defaultMode: 0640
      - name: monitor-password
        secret:
          secretName: {{ include "postgresql-cluster.monitorPassword.secretName" . }}
          defaultMode: 0640
      - name: user-passwords
        secret:
          secretName: {{ include "postgresql-cluster.userPasswords.secretName" . }}
          defaultMode: 0640
      - name: pool-passwd
        emptyDir: {}
      - name: tls
        secret:
          secretName: {{ include "postgresql-cluster.tls.secretName" . }} 
          defaultMode: 0640
      - name: scripts
        configMap:
          name: {{ $fullname }}-scripts
          defaultMode: 0774
          items:
          - key: wait-for-host.sh
            path: wait-for-host.sh
          - key: check-status-of-primary-node.sh
            path: check-status-of-primary-node.sh
          - key: generate-pool-passwd.sh
            path: generate-pool-passwd.sh
      initContainers: 
      - name: wait-for-backend
        image: busybox:1
        imagePullPolicy: IfNotPresent
        command:
        - /opt/wait-for-host.sh
        - --timeout
        - '60'
        - {{ $masterHost }}
        {{- range $i := (until $numOfReplicas) }}
        - {{ printf "%s-standby-%d.%s" $fullname $i $serviceDomain }}
        {{- end }}{{/* range */}}
        volumeMounts:
        - name: scripts
          mountPath: /opt/
          readOnly: true
      - name: generate-pool-passwd
        image: {{ .Values.pgpool.image }}
        imagePullPolicy: IfNotPresent
        command:
        - su-exec
        - postgres
        - /opt/generate-pool-passwd.sh
        - -i
        - /secrets/users
        - -o
        - /var/lib/pgpool/pool-passwd
        volumeMounts:
        - name: scripts
          mountPath: /opt/
          readOnly: true
        - name: user-passwords
          mountPath: /secrets/users
          readOnly: true
        - name: pool-passwd
          mountPath: /var/lib/pgpool/pool-passwd
      containers:
      - image: {{ .Values.pgpool.image }}
        imagePullPolicy: IfNotPresent
        name: pgpool
        env:
        - name: POOL_PASSWD_FILE
          value: /var/lib/pgpool/pool-passwd/pool_passwd
        - name: PGPOOLKEYFILE
          value: /var/lib/pgpool/pool-passwd/key
        - name: PGPOOL_ADMIN_PASSWORD_FILE
          value: /secrets/pgpool-admin-password/password
        - name: MONITOR_PASSWORD_FILE
          value: /secrets/monitor-password/password
        - name: TLS_KEY_FILE
          value: /certs/tls.key
        - name: TLS_CERT_FILE
          value: /certs/tls.crt
        - name: AUTH_METHOD
          value: scram-sha-256 
        - name: NUM_PROCS
          value: '{{ .Values.pgpool.numProcs }}'
        - name: POOL_SIZE
          value: '{{ .Values.pgpool.poolSize }}'
        - name: CHILD_LIFE_TIME
          value: '{{ .Values.pgpool.childLifeTime | default "5min" }}'
        - name: CLIENT_IDLE_LIMIT
          value: '{{ .Values.pgpool.clientIdleLimit | default "0" }}'
        - name: LOAD_BALANCE
          value: '{{ .Values.pgpool.loadBalance | empty | ternary "off" "on" }}'
        - name: BACKEND_0_HOST
          value: {{ $masterHost }}
        - name: BACKEND_0_WEIGHT
          value: '1'
        - name: BACKEND_0_NAME
          value: server0
        {{- if .Values.pgpool.loadBalance }}
        {{- range $i := (until $numOfReplicas) }}
        - name: {{ printf "BACKEND_%d_HOST" ($i| add1) }}
          value: {{ printf "%s-standby-%d.%s" $fullname $i $serviceDomain }}
        - name: {{ printf "BACKEND_%d_WEIGHT" ($i| add1) }}
          value: '1'
        - name: {{ printf "BACKEND_%d_NAME" ($i| add1) }}
          value: {{ printf "server%d" ($i| add1) }}
        {{- end -}}{{/* range */}}
        {{- end }}{{/* if loadBalance */}}
        volumeMounts:
        - name: pgpool-admin-password
          mountPath: /secrets/pgpool-admin-password
          readOnly: true
        - name: monitor-password
          mountPath: /secrets/monitor-password
          readOnly: true
        - name: pool-passwd
          mountPath: /var/lib/pgpool/pool-passwd
          readOnly: true
        - name: tls
          mountPath: /certs
          readOnly: true
        - name: scripts
          mountPath: /opt/
          readOnly: true
        ports:
        - containerPort: 5433
        {{- if .Values.pgpool.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - /opt/check-status-of-primary-node.sh
          initialDelaySeconds: {{ .Values.pgpool.readinessProbe.initialDelaySeconds | default 3 }}
          periodSeconds: {{  .Values.pgpool.readinessProbe.periodSeconds | default 30 }}
        {{- end }}{{/* if .Values.pgpool.readinessProbe.enabled */}}
        terminationMessagePolicy: FallbackToLogsOnError 
        resources:
          {{- toYaml .Values.pgpool.resources | nindent 10 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
        
{{- end }}{{/* if .Values.pgpool.enabled */}}


---
{{- if .Values.psql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-psql
  labels:
    {{- include "postgresql-cluster.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql-cluster.selectorLabelsForCommandLine" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql-cluster.selectorLabelsForCommandLine" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.postgres.securityContext.uid }}
        runAsGroup: {{ .Values.postgres.securityContext.gid }}
        fsGroup: {{ .Values.postgres.securityContext.gid }}
      # shareProcessNamespace because we want SIGTERM to be sent to /pause (as PID 1)
      shareProcessNamespace: true
      volumes:
      - name: pgpass
        secret:
          secretName: {{ $fullname }}-pgpass
          defaultMode: 0640
      - name: home
        emptyDir: {}      
      initContainers:
      - name: prepare-home
        image: {{ .Values.postgres.image }}
        command:
        - sh
        args:
        - -c
        - |-
          cp -v /pgpass ${HOME}/.pgpass && chmod -v 0600 ${HOME}/.pgpass
        volumeMounts:
        - name: pgpass
          mountPath: /pgpass
          subPath: pgpass
          readOnly: true
        - name: home
          mountPath: /var/lib/postgresql
      containers:
      - name: psql
        image: {{ .Values.postgres.image }}
        env:
        - name: PGHOST
          value: {{ $masterHost }}
        volumeMounts:
        - name: home
          mountPath: /var/lib/postgresql
        command:
        - sleep
        - infinity
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      restartPolicy: Always
      dnsConfig:
        options:
        - name: ndots
          value: "1"
{{ end }}{{/* if .Values.psql.enabled */}}
