# vim: set filetype=helm: 

{{- $fullname := (include "postgresql-cluster.fullname" .) -}}

{{- with .Values.postgres.pv }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "archive-%s" $fullname }}
  annotations:
    {{/* https://github.com/helm/helm/issues/6261#issuecomment-523472128 */}}
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .archiveDir.size }}
  storageClassName: {{ .archiveDir.storageClassName }}
  volumeMode: Filesystem
  {{- if .archiveDir.useSelector }}
  selector:
    matchLabels:
      {{- include "postgresql-cluster.selectorLabels" $ | nindent 6 }}  
      {{- if .archiveDir.extraMatchLabels }}{{ toYaml .archiveDir.extraMatchLabels | nindent 6 }}{{- end }}
  {{- end }}{{/* if .archiveDir.useSelector */}}
{{- end }}{{/* with .Values.postgres.pv */}}
