# vim: set filetype=helm:

{{- $generatedPostgresPassword := "" -}}
{{- $generatedReplicationPassword := "" -}}
{{- $generatedMonitorPassword := "" -}}
{{- $generatedPgpoolAdminPassword := "" -}}

{{- if .Values.postgresPassword.generatePassword }}
{{- $generatedPostgresPassword = randAlphaNum 20 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.postgresPassword.secretName" . }}
  labels: 
    {{- include "postgresql-cluster.hookLabels" . | nindent 4 }}
  annotations:
    {{- include "postgresql-cluster.hookAnnotationsForPassword" . | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $generatedPostgresPassword }}
{{- end }}{{/* if .Values.postgresPassword.generatePassword */}}


{{- if .Values.replicationPassword.generatePassword }}
{{- $generatedReplicationPassword = randAlphaNum 20 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.replicationPassword.secretName" . }}
  labels:
    {{- include "postgresql-cluster.hookLabels" . | nindent 4 }}
  annotations:
    {{- include "postgresql-cluster.hookAnnotationsForPassword" . | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $generatedReplicationPassword }}
{{- end }}{{/* if .Values.replicationPassword.generatePassword */}}


{{- if .Values.monitorPassword.generatePassword }}
{{- $generatedMonitorPassword = randAlphaNum 20 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.monitorPassword.secretName" . }}
  labels:
    {{- include "postgresql-cluster.hookLabels" . | nindent 4 }}
  annotations:
    {{- include "postgresql-cluster.hookAnnotationsForPassword" . | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $generatedMonitorPassword }}
{{- end }}{{/* if .Values.monitorPassword.generatePassword */}}


{{- if .Values.pgpoolAdminPassword.generatePassword }}
{{- $generatedPgpoolAdminPassword = randAlphaNum 20 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.pgpoolAdminPassword.secretName" . }}
  labels:
    {{- include "postgresql-cluster.hookLabels" . | nindent 4 }}
  annotations:
    {{- include "postgresql-cluster.hookAnnotationsForPassword" . | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $generatedPgpoolAdminPassword }}
{{- end }}{{/* if .Values.pgpoolAdminPassword.generatePassword */}}


{{/* Generate pgpass for psql Pod */}}
{{- define "postgresql-cluster.pgpass" -}}
{{ printf "%s-master-0.%s:5432:*:postgres:%s" $.fullname $.serviceDomain $.postgresPassword }}
{{ range $i := until (int $.Values.postgres.replicas) }}
{{- printf "%s-standby-%d.%s:5432:*:postgres:%s" $.fullname $i $.serviceDomain $.postgresPassword }}
{{ end }}{{/* range $i */}}
{{ range $username, $password := $.userPasswords }}
{{- printf "%s-master-0.%s:5432:*:%s:%s" $.fullname $.serviceDomain $username $password }}
{{ range $i := until (int $.Values.postgres.replicas) }}
{{- printf "%s-standby-%d.%s:5432:*:%s:%s" $.fullname $i $.serviceDomain $username $password }}
{{ end -}}{{/* range $i */}}
{{- printf "%s-pgpool.%s:5433:*:%s:%s" $.serviceName $.clusterDomain $username $password }}
{{ end }}{{/* range $.userPasswords */}}
{{- end }}{{/* define "postgresql-cluster.pgpass" */}}

{{- if .Values.psql.enabled }}
{{- $fullname := include "postgresql-cluster.fullname" . -}}
{{- $clusterDomain := include "postgresql-cluster.clusterDomain" . -}}
{{- $serviceName := include "postgresql-cluster.postgres.serviceName" . -}}
{{- $serviceDomain := include "postgresql-cluster.postgres.serviceDomain" . -}}
{{- $ctx := dict "Values" .Values "fullname" $fullname "clusterDomain" $clusterDomain "serviceName" $serviceName "serviceDomain" $serviceDomain }}
{{- $postgresPasswordSecretName := include "postgresql-cluster.postgresPassword.secretName" . }}
{{- $postgresPasswordSecret := lookup "v1" "Secret" .Release.Namespace $postgresPasswordSecretName }}
{{- $postgresPassword := "" }}
{{- if $postgresPasswordSecret }}
  {{- $postgresPassword = (get $postgresPasswordSecret "data").password | b64dec }}
{{- else if $generatedPostgresPassword }}
  {{- $postgresPassword = $generatedPostgresPassword }}
{{- end }}{{/* if $postgresPasswordSecret */}}
{{- $_ := set $ctx "postgresPassword" $postgresPassword }}
{{- $userPasswordsSecret := lookup "v1" "Secret" .Release.Namespace .Values.userPasswords.secretName }}
{{- $userPasswords := dict }}
{{- if $userPasswordsSecret }}
  {{- range $username, $password := (get $userPasswordsSecret "data") }}
    {{- $_ := set $userPasswords $username ($password | b64dec) }}
  {{- end }}
{{- end }}{{/* if $userPasswordsSecret */}}
{{- $_ := set $ctx "userPasswords" $userPasswords }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-pgpass
  labels:
    {{- include "postgresql-cluster.labels" . | nindent 4 }}
data:
  pgpass: {{ (include "postgresql-cluster.pgpass" $ctx) | b64enc }}
{{- end }}{{/* if .Values.psql.enabled */}}
