# vim: set filetype=helm: 

{{- $command := list "postgres" "-c" "config_file=$(CONFIG_FILE)" -}}
{{/* https://stackoverflow.com/a/66548354/1943126 */}}
{{- if .Values.postgres.maxNumConnections }}
{{- $command = append $command (printf "--max_connections=%d" (int .Values.postgres.maxNumConnections)) -}}
{{- end }}{{/* if .maxNumConnections */}}
{{- if .Values.postgres.sharedBuffersSize }}
{{- $command = append $command (printf "--shared_buffers=%s" .Values.postgres.sharedBuffersSize) }}
{{- end }}{{/* if .sharedBuffersSize */}}
{{- if .Values.postgres.workMemory }}
{{- $command = append $command (printf "--work_mem=%s" .Values.postgres.workMemory) -}}
{{- end }}{{/* if .workMemory */}}

{{- $fullname := (include "postgresql-cluster.fullname" .) -}}
{{- $serviceName := (include "postgresql-cluster.postgres.serviceName" .) -}}
{{- $serviceDomain := (include "postgresql-cluster.postgres.serviceDomain" .) -}}
{{- $masterHost := printf "%s-master-0.%s" $fullname $serviceDomain -}}

{{- $configMap := (include (print $.Template.BasePath "/configmaps/config.yml") . | fromYaml) -}}

{{- $readinessProbeCommand := list "su-exec" "postgres" "pg_isready" "-h" "localhost" -}}

# manifests
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullname }}-master
  labels:
    {{- include "postgresql-cluster.labelsForMaster" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ $serviceName }}
  selector:
    matchLabels:
      {{- include "postgresql-cluster.selectorLabelsForMaster" . | nindent 6 }}
  {{- with .Values.postgres.volumeClaims }}
  volumeClaimTemplates:
  # PVC template for data directory
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: {{ .dataDir.storageClassName }}
      resources:
        requests:
          storage: {{ .dataDir.size }}
      {{- if .dataDir.useSelector }}
      selector:
        matchLabels:
          {{- include "postgresql-cluster.selectorLabelsForMasterData" $ | nindent 10 }}  
          {{- if .dataDir.extraMatchLabels }}{{ toYaml .dataDir.extraMatchLabels | nindent 10 }}{{- end }}
      {{- end }}{{/* if .dataDir.useSelector */}}
  {{- end }}
  # Pod template
  template:
    metadata:
      annotations:
        checksum/config: {{ cat (get $configMap.data "postgresql.conf") "\n\n" (get $configMap.data "pg_hba.conf") "\n\n" (get $configMap.data "replication-for-master.conf") | sha256sum }}
        {{- if .Values.podAnnotations }}{{ toYaml .Values.podAnnotations | nindent 8 }}{{- end }}
        {{- if .Values.postgres.podAnnotations }}{{ toYaml .Values.postgres.podAnnotations | nindent 8 }}{{- end }}
      labels:
        {{- include "postgresql-cluster.selectorLabelsForMaster" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "postgresql-cluster.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.postgres.securityContext.gid }}
      volumes:
      - name: archive
        persistentVolumeClaim:
          claimName: {{ include "postgresql-cluster.postgres.archivePvcName" . }}
      - name: postgres-password
        secret:
          secretName: {{ include "postgresql-cluster.postgresPassword.secretName" . }}
          defaultMode: 0640
      - name: monitor-password
        secret:
          secretName: {{ include "postgresql-cluster.monitorPassword.secretName" . }}
          defaultMode: 0640
      - name: replication-password
        secret:
          secretName: {{ include "postgresql-cluster.replicationPassword.secretName" . }}
          defaultMode: 0640
      - name: user-passwords
        secret:
          secretName: {{ include "postgresql-cluster.userPasswords.secretName" . }}
          defaultMode: 0640
      - name: tls
        secret:
          secretName: {{ include "postgresql-cluster.tls.secretName" . }} 
          defaultMode: 0640
      - name: config
        configMap:
          name: {{ $fullname }}-config-generated
      {{- if .Values.postgres.configurationFrom }}
      - name: config-extra
        configMap:
          name: {{ .Values.postgres.configurationFrom.configMapKeyRef.name }}
      {{- end }}
      - name: db-init-scripts
        configMap:
          name: {{ $fullname }}-db-init-scripts
          defaultMode: 0774
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image }}"
        imagePullPolicy: IfNotPresent
        args: {{- toYaml $command | nindent 10 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: POSTGRES_INITDB_ARGS
          value: >-
            --data-checksums
        - name: CONFIG_FILE
          value: /etc/postgresql/postgresql.conf
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/postgres-password/password
        - name: REPLICATION_USER
          value: replicator
        - name: REPLICATION_PASSWORD_FILE
          value: /secrets/replication-password/password
        - name: MONITOR_USER
          value: monitor
        - name: MONITOR_PASSWORD_FILE
          value: /secrets/monitor-password/password
        - name: USER_PASSWORDS_DIR
          value: /secrets/users
        - name: ARCHIVE_DIR
          value: /var/backups/postgresql/archive
        - name: TLS_KEY_FILE
          value: /certs/tls.key
        - name: TLS_CERT_FILE
          value: /certs/tls.crt
        volumeMounts: 
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: archive
          mountPath: /var/backups/postgresql/archive
          subPathExpr: $(POD_NAME)
        - name: postgres-password
          mountPath: /secrets/postgres-password
          readOnly: true
        - name: replication-password
          mountPath: /secrets/replication-password
          readOnly: true
        - name: monitor-password
          mountPath: /secrets/monitor-password
          readOnly: true
        - name: user-passwords
          mountPath: /secrets/users
          readOnly: true
        - name: tls
          mountPath: /certs
          readOnly: true
        - name: config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
          readOnly: true
        - name: config
          mountPath: /etc/postgresql/pg_hba.conf
          subPath: pg_hba.conf
          readOnly: true
        - name: config
          mountPath: /etc/postgresql/conf.d/01-replication.conf
          subPath: replication-for-master.conf
          readOnly: true
        {{- if .Values.postgres.configurationFrom }}
        {{- range $i, $key := .Values.postgres.configurationFrom.configMapKeyRef.key }}
        {{- if (hasSuffix ".conf" $key) }}
        - name: config-extra
          mountPath: {{ printf "/etc/postgresql/conf.d/99-x%d-%s" $i $key }}
          subPath: {{ $key }}
          readOnly: true
        {{- end }}{{/* if (hasSuffix ".conf" $key) */}}
        {{- end }}{{/* range */}}
        {{- end }}{{/* if .Values.postgres.configurationFrom */}}
        - name: db-init-scripts
          mountPath: /docker-entrypoint-initdb.d 
          readOnly: true
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe: null
        readinessProbe:
          exec:
            command: {{- toYaml $readinessProbeCommand | nindent 14 }} 
          initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds | default 3 }}
          periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds | default 20 }}
        terminationMessagePolicy: FallbackToLogsOnError 
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
      affinity:
        {{- toYaml (.Values.postgres.master.affinity | default .Values.affinity) | nindent 8 }}


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullname }}-standby
  labels:
    {{- include "postgresql-cluster.labelsForStandby" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  serviceName: {{ $serviceName }}
  selector:
    matchLabels:
      {{- include "postgresql-cluster.selectorLabelsForStandby" . | nindent 6 }}
  {{- with .Values.postgres.volumeClaims }}
  volumeClaimTemplates:
  # PVC template for data directory
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: {{ .dataDir.storageClassName }}
      resources:
        requests:
          storage: {{ .dataDir.size }}
      {{- if .dataDir.useSelector }}
      selector:
        matchLabels:
          {{- include "postgresql-cluster.selectorLabelsForStandbyData" $ | nindent 10 }}  
          {{- if .dataDir.extraMatchLabels }}{{ toYaml .dataDir.extraMatchLabels | nindent 10 }}{{- end }}
      {{- end }}{{/* if .dataDir.useSelector */}}
  {{- end }}
  # Pod template
  template:
    metadata:
      annotations:
        checksum/config: {{ cat (get $configMap.data "postgresql.conf") "\n\n" (get $configMap.data "pg_hba.conf") "\n\n" (get $configMap.data "replication-for-standby.conf") | sha256sum }}
        {{- if .Values.podAnnotations }}{{ toYaml .Values.podAnnotations | nindent 8 }}{{- end }}
        {{- if .Values.postgres.podAnnotations }}{{ toYaml .Values.postgres.podAnnotations | nindent 8 }}{{- end }}
      labels:
        {{- include "postgresql-cluster.selectorLabelsForStandby" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "postgresql-cluster.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.postgres.securityContext.gid }}
      volumes:
      - name: archive
        persistentVolumeClaim:
          claimName: {{ include "postgresql-cluster.postgres.archivePvcName" . }}
      - name: postgres-password
        secret:
          secretName: {{ include "postgresql-cluster.postgresPassword.secretName" . }}
          defaultMode: 0640
      - name: replication-password
        secret:
          secretName: {{ include "postgresql-cluster.replicationPassword.secretName" . }}
          defaultMode: 0640
      - name: tls
        secret:
          secretName: {{ include "postgresql-cluster.tls.secretName" . }} 
          defaultMode: 0640
      - name: config
        configMap:
          name: {{ $fullname }}-config-generated
      {{- if .Values.postgres.configurationFrom }}
      - name: config-extra
        configMap:
          name: {{ .Values.postgres.configurationFrom.configMapKeyRef.name }}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ $fullname }}-scripts
          defaultMode: 0774
      - name: pgpass
        emptyDir: {}
      initContainers:
      - name: wait-for-master
        image: busybox:1
        imagePullPolicy: IfNotPresent
        command:
        - /opt/wait-for-host.sh
        - --timeout 
        - '30'
        - {{ $masterHost }}
        volumeMounts:
        - name: scripts
          mountPath: /opt/
          readOnly: true
      - name: generate-pgpass
        image: busybox:1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: {{ .Values.postgres.securityContext.uid }}
        env:
        - name: MASTER_HOST
          value: {{ $masterHost }}
        - name: REPLICATION_USER
          value: replicator
        - name: REPLICATION_PASSWORD_FILE
          value: /secrets/replication-password/password
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/postgres-password/password
        - name: PGPASSFILE
          value: /etc/postgresql/pgpass/.pgpass
        command:
        - /opt/generate-pgpass-for-standby.sh
        volumeMounts:
        - name: scripts
          mountPath: /opt/
          readOnly: true
        - name: pgpass
          mountPath: /etc/postgresql/pgpass 
        - name: postgres-password
          mountPath: /secrets/postgres-password
          readOnly: true
        - name: replication-password
          mountPath: /secrets/replication-password
          readOnly: true
      {{- if .Values.postgres.standby.prepareData }}
      - name: prepare-data
        image: "{{ .Values.postgres.image }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: PGPASSFILE
          value: /etc/postgresql/pgpass/.pgpass
        - name: REPLICATION_USER
          value: replicator
        - name: MASTER_HOST
          value: {{ $masterHost }}
        command: 
        - su-exec
        - postgres
        - /opt/prepare-data-for-standby.sh
        volumeMounts:
        - name: pgpass
          mountPath: /etc/postgresql/pgpass
          readOnly: true
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: scripts
          mountPath: /opt/
          readOnly: true
      {{- end }}{{/* if .Values.postgres.standby.prepareData */}}
      - name: generate-name
        image:  "{{ .Values.postgres.image }}"
        imagePullPolicy: IfNotPresent
        {{/*- see https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-SYNCHRONOUS-STANDBY-NAMES -*/}}
        command:
        - su-exec
        - postgres
        - bash
        - -c
        - |-
          printf "cluster_name = '%s'\n" ${HOSTNAME//-/_} > ${PGDATA}/01-cluster-name.conf
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      containers: 
      - name: postgres
        image: "{{ .Values.postgres.image }}"
        imagePullPolicy: IfNotPresent
        args: {{- toYaml $command | nindent 10 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: CONFIG_FILE
          value: /etc/postgresql/postgresql.conf
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/postgres-password/password
        - name: ARCHIVE_DIR
          value: /var/backups/postgresql/archive
        - name: ARCHIVE_MASTER_DIR
          value: /var/backups/postgresql/archive-master
        - name: TLS_KEY_FILE
          value: /certs/tls.key
        - name: TLS_CERT_FILE
          value: /certs/tls.crt
        - name: PGPASSFILE
          value: /etc/postgresql/pgpass/.pgpass
        volumeMounts: 
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: archive
          mountPath: /var/backups/postgresql/archive-master
          subPathExpr: {{ printf "%s-master-0" $fullname }}
          readOnly: true
        - name: archive
          mountPath: /var/backups/postgresql/archive
          subPathExpr: $(POD_NAME)
        - name: postgres-password
          mountPath: /secrets/postgres-password
          readOnly: true
        - name: tls
          mountPath: /certs
          readOnly: true
        - name: config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
          readOnly: true
        - name: config
          mountPath: /etc/postgresql/pg_hba.conf
          subPath: pg_hba.conf
          readOnly: true
        - name: pgpass
          mountPath: /etc/postgresql/pgpass 
        - name: config
          mountPath: /etc/postgresql/conf.d/01-replication.conf
          subPath: replication-for-standby.conf
          readOnly: true
        {{- if .Values.postgres.configurationFrom }}
        {{- range $i, $key := .Values.postgres.configurationFrom.configMapKeyRef.key }}
        {{- if (hasSuffix ".conf" $key) }}
        - name: config-extra
          mountPath: {{ printf "/etc/postgresql/conf.d/99-x%d-%s" $i $key }}
          subPath: {{ $key }}
          readOnly: true
        {{- end }}{{/* if (hasSuffix ".conf" $key) */}}
        {{- end }}{{/* range */}}
        {{- end }}{{/* if .Values.postgres.configurationFrom */}}
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe: null
        readinessProbe:
          exec:
            command: {{- toYaml $readinessProbeCommand | nindent 14 }} 
          initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds | default 3 }}
          periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds | default 20 }}
        terminationMessagePolicy: FallbackToLogsOnError 
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
      affinity:
        {{- toYaml (.Values.postgres.standby.affinity | default .Values.affinity) | nindent 8 }}
