# vim: set filetype=helm:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}-config-generated
data:
  postgresql.conf: |+
    {{- .Files.Get "files/config/postgresql.conf" | nindent 4 }}
  pg_hba.conf: |+
    {{- .Files.Get "files/config/pg_hba.conf" | nindent 4 }}
  replication-for-master.conf: |+
    {{- include "postgresql-cluster.postgres.configurationStanzaForReplicationInMaster" . | nindent 4 }}
  replication-for-standby.conf: |+
    {{- include "postgresql-cluster.postgres.configurationStanzaForReplicationInStandby" . | nindent 4 }}

