# vim: set filetype=helm:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}-db-init-scripts
data:
  {{- (.Files.Glob "files/db-init-scripts/*.sh").AsConfig | nindent 2 }}

