# vim: set filetype=helm:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}-scripts
data:
  {{- (.Files.Glob "files/scripts/*.sh").AsConfig | nindent 2 }}

