name: CI
run-name: Run continuous-integration tasks

on: 
  push:
    branches:
    - 'pgpool*'
    tags:
    - '0.*'
    - '1.*'

jobs:

  build_image:
    runs-on: ubuntu-20.04
    env:
      pgpool_version: "4.4"
    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/opertusmundi/pgpool
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: ./pgpool/redhat/
        file: pgpool/redhat/Dockerfile
        push: true
        tags: |
          ghcr.io/opertusmundi/pgpool:${{ github.ref_name }}-${{ env.pgpool_version }}-redhat
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

